### PR TITLE
Fix sticky header

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Always use sticky header (rather than fixed), as anything can appear above it (cookie consent message, etc)

Also, don't show anonymous sign in bar if signed in

### CODE REVIEW

**Comment by AlbertoElias** [comment]
I believe sticky only works on some browsers. So what exactly is the change in behaviour?

**Comment by ironsidevsquincy** [comment]
Header is only sticky if browser understands `position: sticky`

**Comment by AlbertoElias** [comment]
But what does that allow you that you can't do without it?

**Comment by ironsidevsquincy** [comment]
I'm not sure I understand the question...
If a browser can do native 'stickiness', than the header sticks to the top of the screen as the user scrolls, otherwise it just scrolls up with the page

**Comment by AlbertoElias** [comment]
But what does that have to do with the cookie message or anything that's above the header, or what was the exact issue you were having that his fixes?

**Comment by ironsidevsquincy** [comment]
`position: fixed` on the header is equivalent to `position: sticky`, if there is nothing above it. As soon as you put something above it (cookie message, whatever), it is no longer equivalent

nyct53oznt

**Comment by AlbertoElias** [comment]
Oh, right! Thanks for the explanation!

**Pull request merged**
