### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to 549561140bdba751f2f207116c30a5edaff4f04c
css, master: 4.55kb decrease (-0.32kb/gzip)
css, internal: 4.58kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Comment by chee** [comment]
> These 3 headings should be h2 right? the h1 is `# o-header`

lol quick work

**Comment by notlee** [comment]
> > These 3 headings should be h2 right? the h1 is `# o-header`
> 
> lol quick work

😅

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to fcd20774e6f274a01ea0f92d2d70477436c76a78
css, master: 4.55kb decrease (-0.32kb/gzip)
css, internal: 4.58kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Pull request merged**
