### PR TITLE
use o-normalise

### PR DESCRIPTION
**Pull request by gvonkoss**

### CODE REVIEW

**Comment by notlee** [comment]
Introducing a new dependancy would usually be a breaking, but I guess as there is only one major (v1) this is okay...

**Comment by leggsimon** [comment]
> Introducing a new dependancy would usually be a breaking

Why? It doesn't change any existing functionality?

**Comment by notlee** [comment]
@leggsimon Introducing a new dependency or bumping a major could cause dependency conflicts.

**Comment by leggsimon** [comment]
Ahhh yes, I forgot about the dep resolution stuff

**Pull request merged**
