### PR TITLE
Increase: Toggle button touch target area

### PR DESCRIPTION
**Pull request by andygout**
@kavanagh 

##### From (hamburger):
hamburger from

##### To (hamburger):
hamburger to

##### From (loupe):
loupe from

##### To (loupe):
loupe to

### CODE REVIEW

**Comment by kavanagh** [comment]
Umm, is this just FYI or do you need me to comment? Thanks if it's the former.

**Comment by andygout** [comment]
Comments pls.

**Comment by kavanagh** [comment]
It's a slight visual improvement but do we want the outline at all?

It means you get a weird behaviour after clicking the loupe. Slightly after clicking the loupe the search field receives focus so you get a click flicker. Also it's not clear (or consistent) that the search field is focused. And the reverse when clicking the search X button - I'm left with the loupe focused even though I just clicked close.

I'm not suggesting changing how things are focused, just the visual cues.

**Comment by andygout** [comment]
The suggested changes are to improve the size of the touch target area for device users.

I wasn't addressing the focus outline issue in this PR (using them more to demonstrate the increased target area), but the outline behaviour remains consistent with what is currently used by Next so suggest that be addressed separately (or in the new nav), but agree that we need consistency for keyboard-only users.

**Comment by alicebartlett** [comment]
This partly addresses @kavanagh's comments but he also wants the actual menu items' touch targets to be bigger too.

Anyway, I'll merge this. Thanks Andy!

**Comment by kavanagh** [comment]
Ah, touch targets, yeah looks good to me.

**Pull request merged**
