### PR TITLE
refactor: do not scope the drawer JS to the header element but the body

### PR DESCRIPTION
**Pull request by i-like-robots**
I reckon drawer toggles may appear in more places soon =]

Also we're not putting the drawer within the header, but the footer for a better core experience.

### CODE REVIEW

**Comment by AlbertoElias** [comment]
What do you mean with the footer thing?

**Comment by i-like-robots** [comment]
If you check out the core experience on Next currently and click the menu link you'll scroll down to the bottom of the page to find the drawer content.

**Comment by AlbertoElias** [comment]
That´s currently supported in the o-header drawer

**Comment by i-like-robots** [comment]
This is line causing the issue, it's scoped so we can't move the drawer to the footer: https://github.com/Financial-Times/o-header/blob/be6a375a6aa8fa5470346af7f6f89280ad48b819/src/js/drawer.js#L125

I made the remaining scope changes as I'm trying to foresee any future issues (and a little more simple).

**Comment by AlbertoElias** [comment]
Oh, that is broken, it should be drawerEl.querySelector. But in the demo, the drawer is outside of the header. Just want to confirm all this is good before merging

**Comment by i-like-robots** [comment]
All working locally for me!

**Pull request merged**
