### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-header/issues/343

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to 16897d83babf421c419fa5b1b603754ca8339914
css, master: 4.6kb decrease (-0.32kb/gzip)
css, internal: 4.59kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to 718dc277265ee103abd102a83526ab06e4374c80
css, master: 4.55kb decrease (-0.32kb/gzip)
css, internal: 4.58kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to fc37ff560382f0763ccf8977ddc88ff1e2610807
css, master: 4.6kb decrease (-0.32kb/gzip)
css, internal: 4.59kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to e20b1de18d4564a9662620d0ee4f2dba4e4ccadd
css, master: 4.55kb decrease (-0.32kb/gzip)
css, internal: 4.58kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to 1b490772f5649b1b03117022071128d09bfda105
css, master: 4.55kb decrease (-0.32kb/gzip)
css, internal: 4.58kb decrease (-0.35kb/gzip)
An insignificant difference was also found for: js

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to 3af361752fbd865fe94582a07670f1a8e70e445e
js: 0.34kb increase (0.13kb/gzip)
css, master: 0.72kb decrease (-0.00kb/gzip)

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to 27af73ee918fd8edee18be0fd493f1956f651b49
js: 0.33kb increase (0.12kb/gzip)
css, master: 0.59kb decrease (0.02kb/gzip)

**Comment by origamiserviceuser** [comment]
o-header bundle size difference from 7.8.12 to b999fe885c695058c278f02d0eee04ae47cea3a2
js: 0.27kb increase (0.10kb/gzip)
css, master: 0.65kb decrease (-0.00kb/gzip)

**Comment by notlee** [comment]
This [was](https://github.com/Financial-Times/o-header/pull/356) [reviewed](https://github.com/Financial-Times/o-header/pull/354) [in previous PRs](https://github.com/Financial-Times/o-header/pull/351)

**Pull request merged**
