### PR TITLE
better label for useful tools

### PR DESCRIPTION
**Pull request by wheresrhys**
@AlbertoElias Could still be improved. Just opening this to start the discussion

### CODE REVIEW

**Comment by AlbertoElias** [comment]
If nobody objects to this, I'm happy to go with it. I really don't mind the specifics as those links are really up to the product

**Comment by wheresrhys** [comment]
mmm true. Maybe the default text shoudl point people to a 'guidelines on writing accessibility text' page or something

**Comment by AlbertoElias** [comment]
Done in #144 Can I close this?

**Comment by wheresrhys** [comment]
yip

On 14 March 2016 at 16:30, Alberto Elias <notifications@github.com> wrote:

> Done in #144 <https://github.com/Financial-Times/o-header/pull/144> Can I
> close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-header/pull/135#issuecomment-196399533>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Pull request closed without merging**
