### PR TITLE
Use `o-icons`

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Rather than `o-ft-icons`

### CODE REVIEW

**Comment by onishiweb** [comment]
Just fixed the failing tests, which was an unrelated issue to the switch to `o-icons`.

However, just tried this locally and noticed that the output of `o-icons` is slightly different to `o-ft-icons` and is causing an issue with the height of the masthead on the light and minimal themes. Looking into this now.

**Comment by onishiweb** [comment]
Demos aren't working because the new `oIconsGetIcon` mixin, even when using `$apply-base-styles: false` outputs a height property. I'm not sure why this is the case though. 

@ironsidevsquincy if this is needed soon, we can fix this by overriding the heights after including the icon. Otherwise, it might need a chat with Alberto to see why the icon mixin is outputting the height as well.

**Comment by ironsidevsquincy** [comment]
Ok, updated the usage of the mixin to pass in the height, so now visually working.

Opened an issue in `o-icons` around this - https://github.com/Financial-Times/o-icons/issues/10

**Comment by onishiweb** [comment]
Thanks @ironsidevsquincy this looks good. Will merge and release now.

**Comment by onishiweb** [comment]
There's a PR open (https://github.com/Financial-Times/o-icons/pull/9) that will fix the issue on `o-icons` as well, so this should be fixed soon

**Pull request merged**
